/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package middleletters_java;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void test_returnAstring(){
        App letters = new App();
        assertEquals("es", letters.get_middle("test"));
    }

    @Test
    public void test_wordtesting(){
        App letters = new App();
        assertEquals("es", letters.get_middle("test"));
        assertEquals("t", letters.get_middle("testing"));
        assertEquals("dd", letters.get_middle("middle"));
        assertEquals("A", letters.get_middle("A"));
        assertEquals("of", letters.get_middle("of"));
    }

    
}
